Creation des différentes tables pour l'appli magasin
B4va/ecommerce-rmi-iutm pull request #3
Opened 2021-02-14 22:12 UTC by Pythoud-dev

Dite moi si la creation des tables est ok, je ferait les insert si c'est bon pour vous.

2021-02-15 07:36 UTC, B4va reviewed
Quelques petits commentaires sur la forme, mais globalement ça me semble bon sinon 👍

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +create table Boutiques (
Pour garder une cohérence avec ce qu'a fait Alexis, je recommande de partir sur le même format pour le nommage : tout en minuscules, au singulier, avec des underscores si besoin. Ici : `boutique` donc ;)

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +create table Clients (
Idem : `client`.

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +create table Articles (
Idem : `article`.

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +create table Commandes (
Idem : `commande`.

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +create table Quantite (
Ici on était partis sur une classe `ArticleCommande`, recommande donc `article_commande` ;)

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +    motDePasse varchar
Majuscules ? `VARCHAR`

2021-02-15 07:36 UTC, B4va commented on database/init-magasin.sql
> +    imageBlob oid NOT NULL,
Pas obligé le `NOT NULL`, on n'en a pas mis ailleurs. Majuscules ? `OID`

2021-02-17 16:44 UTC, B4va requested changes

2021-02-17 16:44 UTC, B4va commented on database/init-magasin.sql
> +    motDePasse varchar
plutôt `mot_de_passe`

2021-02-17 16:44 UTC, B4va commented on database/init-magasin.sql
> +    id SERIAL PRIMARY KEY,
juste `id` ? idem pour les autres tables

2021-02-21 17:04 UTC, Pythoud-dev commented
Ok je viens de commit, normalement c'est bon

2021-02-21 18:29 UTC, B4va approved these changes

2021-02-21 18:29 UTC, merged